info:
  name: Approve TT77 Config Request
  type: http
  seq: 4

http:
  method: post
  url: "{{individual_admin_host}}/tt77-request/approve"
  headers:
    - name: platform
      value: WEB
    - name: Authorization
      value: Bearer {{individual_admin_token}}
  body:
    type: json
    data: |
      {
        "entityId": "2a35ec16-9473-4bf9-8092-301b6934345b",
        "workflowId": "56263f1c-abf2-449f-b3f0-f1a5a2345fc8",
        "comment": "Approved"
      }

settings:
  encodeUrl: false
  timeout: 0
  followRedirects: true
  maxRedirects: 5
