info:
  name: Approve TT77 Config Request
  type: http
  seq: 4

http:
  method: post
  url: "{{individual_admin_host}}/tt77-request/approve"
  headers:
    - name: platform
      value: WEB
    - name: Authorization
      value: Bearer {{individual_admin_branch_token}}
  body:
    type: json
    data: |
      {
        "entityId": "b4aaff08-8700-481c-8373-86c561a1d1b3",
        "workflowId": "c2d18204-d8a8-4afc-b185-a674a9dd07b2",
        "comment": "Approved"
      }

settings:
  encodeUrl: false
  timeout: 0
  followRedirects: true
  maxRedirects: 5
