info:
  name: Get TT77 Config Request Details
  type: http
  seq: 1

http:
  method: GET
  url: "{{individual_admin_host}}/tt77-request/662b7a03-ad34-4884-a90f-db212023f30e"
  headers:
    - name: platform
      value: WEB
    - name: Authorization
      value: Bearer {{individual_admin_token}}

settings:
  encodeUrl: false
  timeout: 0
  followRedirects: true
  maxRedirects: 5
