info:
  name: Reject TT77 Config Request
  type: http
  seq: 7

http:
  method: post
  url: "{{individual_admin_host}}/tt77-request/reject"
  headers:
    - name: platform
      value: WEB
    - name: Authorization
      value: Bearer {{individual_admin_token}}
  body:
    type: json
    data: |
      {
        "entityId": "dd1154d7-93ae-40ed-8b40-7d28d36b789f",
        "workflowId": "5026bbff-bc7a-43ba-8ff8-4ac897f2c844",
        "comment": "Approved"
      }

settings:
  encodeUrl: false
  timeout: 0
  followRedirects: true
  maxRedirects: 5
